[package]
name = "steward"
version = "0.1.0"
edition = "2024"
rust-version = "1.88"

authors = ["Vasilios Syrakis <syrakis@pm.me>"]
description = "High-performance Envoy rate-limit service in Rust"
repository = "https://github.com/cetanu/steward"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# gRPC
tonic = { version = "0.14.6", features = ["transport"] }
tonic-prost = "0.14.6"
tokio = { version = "1.53.1", features = ["macros", "rt-multi-thread", "signal", "sync", "time"] }
tokio-stream = { version = "0.1.18", features = ["net"] }
socket2 = { version = "0.6.5", features = ["all"] }

# http
reqwest = { version = "0.13.5", features = ["json"] }

# Database
redis = { version = "1.7.1", features = ["tokio-comp", "connection-manager", "script"] }

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Protobufs
prost = "0.14.4"
prost-types = "0.14.4"

# Reading config from disk
config = "0.15.27"

# Logging
tracing = "0.1"
tracing-subscriber = { version = "0.3.23", features = ["json", "env-filter"] }

# Metrics
cadence = "1.8.0"
ring = "0.17"

[dev-dependencies]
reqwest = { version = "0.13.5", features = ["json"] }
tokio = { version = "1.53.1", features = ["macros", "rt-multi-thread", "time"] }

[build-dependencies]
tonic-prost-build = "0.14.6"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = "symbols"
