version: '2.3'

services:
  server:
    build:
      context: .
      dockerfile: containers/Dockerfile
    ports:
      - 5001:5001
    links:
      - redis
    environment:
      RUST_LOG: DEBUG

  envoy:
    build:
      context: containers
      dockerfile: envoy.Dockerfile
    links:
      - server
      - httpbin
    working_dir: /app
    ports:
      - 9901:9901
      - 80:8080
    expose:
      - 9901
      - 80
    environment:
      ENVOY_UID: '0'

  httpbin:
    image: kennethreitz/httpbin

  redis:
    image: redis
    ports:
      - 6379:6379
    expose:
      - 6379
