services:
  server:
    build:
      context: .
      dockerfile: containers/Dockerfile
    ports:
      - 5001:5001
    links:
      - redis
      - mock_config
    environment:
      RUST_LOG: steward=INFO

  envoy:
    build:
      context: containers
      dockerfile: envoy.Dockerfile
    links:
      - server
      - httpbin
    ports:
      - "127.0.0.1:9901:9901"
      - 8080:8080
    expose:
      - 9901
      - 80
    environment:
      ENVOY_UID: '0'

  httpbin:
    image: kennethreitz/httpbin

  redis:
    image: redis
    ports:
      - "127.0.0.1:6379:6379"
    expose:
      - 6379

  mock_config:
    build:
      context: containers
      dockerfile: mock_config.Dockerfile
    ports:
      - 8000:8000
    expose:
      - 8000
