FROM debian:bookworm-slim
RUN apt-get update \
    && apt-get install --no-install-recommends --yes ca-certificates \
    && rm -rf /var/lib/apt/lists/* \
    && groupadd --gid 10001 steward \
    && useradd --uid 10001 --gid 10001 --create-home --home-dir /home/steward --shell /usr/sbin/nologin steward

WORKDIR /project
COPY --chown=10001:10001 containers/steward.yaml steward.yaml
COPY --chown=10001:10001 target/release/steward /project/steward

USER 10001:10001
EXPOSE 5001

CMD [ "/project/steward" ]
