FROM ubuntu:noble
RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends --yes ca-certificates \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /project
COPY containers/steward.yaml steward.yaml
COPY target/release/steward /project/steward

CMD [ "/project/steward" ]
